### ISSUE TITLE
Does Scala 3.2 use same standard library as 2.13?

### ISSUE THREAD

**Issue by doehyunbaek** [scala/scala-library-next#142]
Hi. I'm new to scala and was a little curious whether scala 3.2 uses standard library of scala 2.13.

It seems that when I use code navigation facility of vscode metals plugin in scala 3 project, it directs to scala 2 library, and this repo's README also says 
```
To help users transition from Scala 2 to 3, Scala 2.13 and 3.0 will share the same standard library.
```
this.

Is this still true as scala3 have upgraded past 3.1 and 3.2? Couldn't get any clear info regarding this topic, though maybe obvious to scala users.

Please close this issue if it's not appropriate or my question is answered. If you need a pr editing the README let me know. Thanks in advance.

**Comment by BalmungSan** [comment]
> Is this still true as scala3 have upgraded past 3.1 and 3.2?

Yes.

**Comment by doehyunbaek** [comment]
Thanks for your answer. Closing.
