### ISSUE TITLE
Initial repo setup

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-library-next#2]
* [x] Push initial skeleton with license and such
* [x] Disable unwanted GitHub features such as wiki
* [x] Grant access to appropriate teams and/or individuals
* [x] Add it to readme at https://github.com/scala/sbt-scala-module
* [x] Add `build.sbt` with `sbt-scala-module` (#6)
* [x] Make sure Travis-CI works (https://travis-ci.org/scala/scala-library-next)
* [x] Add it to the Scala 2.13 community build (https://github.com/scala/community-build/pull/1264)
* [x] Add it to scala-steward (https://github.com/scala-steward-org/repos/pull/468)
* [x] Add publishing secrets to Travis-CI config, following [sbt-ci-release instructions](https://github.com/olafurpg/sbt-ci-release/blob/master/readme.md)
* [x] Try out publishing to make sure it works
  * but drop the staging repos so nothing actually publishes
* [x] Write a proper README (#11)
* [x] Set up labels for use on issues
* [x] Reference it from the scala/scala README (https://github.com/scala/scala/pull/9273)

**Comment by NthPortal** [comment]
> Be clear about where discussions on additions should take place

where *should* discussions on additions take place?

**Comment by lrytz** [comment]
>     * Add `build.sbt` with `sbt-scala-module`

Please use scala-xml as starting point, it's the most up to date. In particular, I still have to push https://github.com/scala/scala-xml/pull/417 through all the other module repos.

**Comment by SethTisue** [comment]
update on timing:

a few things cut in front of this in my queue:

* scala-collection-compat release (now done)
* scala-xml release for Dotty (now done)

and still in progress is:

* scala-parallel-collections 1.0 release — harder than expected because we should make sure Dotty support is in place before going 1.0

if the scala-parallel-collections stuff gets too hairy, I might decide to tackle this repo first.

but also, I'm on vacation next week.

so: this is currently on hold, but not for much longer, I'm optimistic I'll get to it before October.

in the meantime, it's fine to start discussion on issues.

**Comment by NthPortal** [comment]
I just realised we didn't determine where discussions on additions should take place yesterday

**Comment by SethTisue** [comment]
Here seems good? (And as with the other issue trackers, if something seems important and/or contentious enough, we call attention it on a Discourse thread, and/or on Twitter, etc.)

Anywhere but scala/bug!

What are the other choices, if any?

**Comment by NthPortal** [comment]
could ask people to open a discourse thread? that seems to be what scala/bug suggests.

I think it's easiest to put them here personally

**Comment by SethTisue** [comment]
I did a round of work on this today. Build is in place, publishing is in place. More soon.

**Comment by NthPortal** [comment]
I will be migrating some issues from scala/bug over

**Comment by SethTisue** [comment]
have at it, everybody!

**Comment by SethTisue** [comment]
> I will be migrating some issues from scala/bug over.

I opened #12 on this

**Comment by SethTisue** [comment]
I made a milestone (0.1.0)
