### ISSUE TITLE
Build should declare a `versionScheme`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-library-next#72]
as per https://scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html and discussion at scala/sbt-scala-module#111

**Comment by BalmungSan** [comment]
Which versioning policy should this project follow? early-semver?

Also, I would guess that more than just adding the `versionScheme` the idea is to also add [**sbt-version-policy**](https://github.com/scalacenter/sbt-version-policy), right?
