### ISSUE TITLE
Add groupMapReduce to Iterator

### ISSUE THREAD

**Issue by sim642** [scala/scala-library-next#8]
Currently `groupMapReduce` is defined in `IterableOps` so it's not available for `Iterator`, but it easily could be because it doesn't require building an inner collection of the collection type, unlike `groupBy` and `groupMap`. Thus `groupMapReduce` would be hoisted to `IterableOnceOps` instead and be a consuming operation on the iterator.

I suppose the current workaround would be to use `to(LazyList)` on an iterator and use `groupMapReduce` on that.

**Comment by NthPortal** [comment]
anyone against this change? (👍 in favour, 👎 against)

**Comment by NthPortal** [comment]
it has been about 2 weeks, with moderate explicit support and no dissent. if there is no dissent by this coming Sunday (2020-12-06), or if we get a couple lightbend approvals before then (without any dissenting opinions), I will consider this proposal accepted.

obviously, we can still come back to it at any later point before release and change things if we decide to

**Comment by SethTisue** [comment]
> I will consider this proposal accepted

Note that I think we should probably hold off on actually merging any PRs here until we have some kind of signoff process. It probably doesn't need to be super formal, but this repo is still pretty new and I don't want standard library additions flying in under people's radar. Where “people” means: the Scala 2 team at Lightbend; the Dotty team at EPFL; and the community.

Off the top of my head: how about a label that indicates that something is considered mergeable? Then every so often, we can publicize that a batch of PRs is ready for hopefully-final review/signoff.

We use to have SLIP for this, but I don't suggest we try to bring that back. The basics I suggest we need are:

* Scala 2 team discusses at their team meeting, if needed.
* Dotty team discusses at their team meeting, if needed.
* There is sufficiently-publicized opportunity for community input.

I think most of the time there will be consensus or near-consensus. If some particular change ends up being sufficiently controversial that it's not clear what to do, well, I guess we can cross that bridge when we come to it :-)

**Comment by NthPortal** [comment]
as context for the fact that I merged this anyway, this comment by Seth [in Gitter](https://gitter.im/scala/contributors?at=60523e1d33346c16275ae3af); I think this is a fairly uncontroversial change, as it just moves the method up the collections hierarchy

**Comment by SethTisue** [comment]
Yeah, that's fine. We can handle things on a case by case basis until we have something written down.
